local RoundManager = require(game.ServerScriptService.RoundManager)
local InventoryManager = require(game.ServerScriptService.InventoryManager)
local MovementValidator = require(game.ServerScriptService.MovementValidator)
local StaminaManager    = require(game.ServerScriptService.StaminaManager)
local QuestManager      = require(game.ServerScriptService.QuestManager)
QuestManager.Init()
RoundManager.Start()
print("✅ GameManager startad!")
