local RoundManager = require(game.ServerScriptService.RoundManager)
local InventoryManager = require(game.ServerScriptService.InventoryManager)
local MovementValidator = require(game.ServerScriptService.MovementValidator)
local StaminaManager    = require(game.ServerScriptService.StaminaManager)
local QuestManager      = require(game.ServerScriptService.QuestManager)
local CloseCallDetector = require(game.ServerScriptService.CloseCallDetector)
local StreakManager     = require(game.ServerScriptService.StreakManager)
local MomentBroadcaster = require(game.ServerScriptService.MomentBroadcaster)
local MapManager        = require(game.ServerScriptService.MapManager)
MapManager.init()
QuestManager.Init()
CloseCallDetector.Init()
StreakManager.Init()
MomentBroadcaster.Init()
RoundManager.Start()
print("✅ GameManager startad!")
